base_model: google/gemma-3-27b-it
strict: false

load_in_4bit: true
load_in_8bit: false

# gemma3 doesn't seem to play nice with ddp
ddp_find_unused_parameters: true

datasets:
  - path: /data/nvme7n1p1/saida/train_t2tt_26_03_v2.jsonl
    type: alpaca
dataset_prepared_path: /data/nvme7n1p1/saida/train_t2tt_26_03_v2_prep_2048

val_set_size: 0.004

output_dir: /data/nvme7n1p1/saida/train_t2tt_09_04_lora_kaz_eng_v1_r256_a512

adapter: lora
lora_model_dir:

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true


lora_r: 512
lora_alpha: 1024
lora_dropout: 0.05
lora_target_modules: 'language_model.model.layers.[\d]+.(mlp|cross_attn|self_attn).(up|down|gate|q|k|v|o)_proj'

wandb_project: gemma3-27b-t2tt-lora
wandb_entity: mamubieke-parehati-ISSAI
wandb_watch:
wandb_name: r_512_alpha_1024
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 4
num_epochs: 5
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
bf16: true
fp16: false
tf32: true

gradient_checkpointing: unsloth
gradient_checkpointing_kwargs:
  use_reentrant: false
local_rank:
logging_steps: 10
flash_attention:
eager_attention: true

warmup_steps: 100
evals_per_epoch: 2
eval_table_size:
saves_per_epoch: 3
debug:
deepspeed: deepspeed_configs/zero2.json
weight_decay: 0.0
fsdp:
fsdp_config: