base_model: google/gemma-3-27b-it
processor_type: AutoProcessor
load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: /data/saida_mussakhojayeva/datasets/json_files/train_t2tt_31_03_all_shuffle.jsonl
    type: alpaca
dataset_prepared_path: /scratch/saida_mussakhojayeva/gemma27b-out/train_t2tt_31_03
ddp_find_unused_parameters: true

val_set_size: 0.003

output_dir: /scratch/saida_mussakhojayeva/gemma27b-out-all-langs_01_04
sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

wandb_project: gemma3-27b-t2tt
wandb_entity: mamubieke-parehati-ISSAI
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 4
eval_batch_size: 2
num_epochs: 5
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 2e-5

train_on_inputs: false
group_by_length: true
bf16: true
fp16: false
tf32: false


gradient_checkpointing: unsloth
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint: /scratch/saida_mussakhojayeva/gemma27b-out-all-langs_01_04/checkpoint-7811/
logging_steps: 1
xformers_attention:
flash_attention: 
eager_attention: true

warmup_steps: 100
evals_per_epoch: 2
eval_table_size:
saves_per_epoch: 2
debug:
deepspeed: deepspeed_configs/zero3_bf16.json
weight_decay: 0.0
fsdp:
fsdp_config:
