base_model: google/gemma-3-27b-it
processor_type: AutoProcessor
strict: false
load_in_8bit: false
load_in_4bit: true
# gemma3 doesn't seem to play nice with ddp
ddp_find_unused_parameters: true

datasets:
  - path: /data/saida_mussakhojayeva/datasets/json_files//train_t2tt_08_04_all.jsonl
    type: alpaca
dataset_prepared_path: /scratch/saida_mussakhojayeva/gemma27b-out/train_t2tt_31_03

val_set_size: 0.004

output_dir: /scratch/saida_mussakhojayeva/train_t2tt_08_04_qlora

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true


lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: 'language_model.model.layers.[\d]+.(mlp|cross_attn|self_attn).(up|down|gate|q|k|v|o)_proj'

wandb_project: gemma3-27b-t2tt-lora
wandb_entity: dhcppc0
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 4
num_epochs: 5
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: true
bf16: true
fp16: false
tf32: false

gradient_checkpointing: unsloth
gradient_checkpointing_kwargs:
  use_reentrant: false
local_rank:
logging_steps: 10
flash_attention:
eager_attention: true

warmup_steps: 100
evals_per_epoch: 2
eval_table_size:
saves_per_epoch: 2
debug:
deepspeed: deepspeed_configs/zero3_bf16.json
weight_decay: 0.0
fsdp:
fsdp_config: